### ISSUE TITLE
"uncurried2 is not a function" after upgrading to 1.0.2

### ISSUE THREAD

**Issue by Phylodome** [dmtrKovalenko/reason-date-fns#144]
Not exactly sure why `uncurried2` is no longer available, but perhaps something in `bs-platform` has changed around compilation of the type definitions used for `uncurried2`?

I'm on `bs-platform@9.0.1` and `date-fns@2.19.0`. 

<img width="440" alt="Screen Shot 2021-03-12 at 2 27 01 PM" src="https://user-images.githubusercontent.com/241837/111005374-899edc00-833f-11eb-912f-10d7a7368874.png">

**Comment by Phylodome** [comment]
After a bit more testing, this actually looks like the break is related to the underlying `date-fns` implementation rather than the `reason-date-fns` implementation.

The error arises when moving from `date-fns@2.16.1` to `date-fns@2.17.0`. Looking at their [changelog](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md), nothing immediately jumps out as an obvious cause. Also, when looking at their codebase as of the `2.16.1` tag, I don't see any results for `uncurried2`, so I'm not precisely certain as to where the underlying function is supposed to come from.
